# Generated by Django 6.1 on 2026-08-09 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('yookassa', 'YooKassa'), ('tinkoff', 'Tinkoff'), ('manual', 'Manual')], default='yookassa', max_length=30)),
                ('provider_id', models.CharField(blank=True, max_length=128)),
                ('payment_type', models.CharField(choices=[('card', 'Card'), ('sbp', 'SBP'), ('cash', 'Cash'), ('invoice', 'Invoice')], default='card', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx')],
                'unique_together': {('provider', 'provider_id')},
            },
        ),
    ]
