"""Shop API correlation fields and a partial uniqueness constraint.

Written by hand rather than autogenerated: ``created_at``/``updated_at`` use
``auto_now_add``/``auto_now``, which makes ``makemigrations`` prompt for a
one-off default. The table is empty, so ``timezone.now`` is a safe explicit
default and keeps the command non-interactive.
"""

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        # 0001 declared this as unique_together, which must be dropped before
        # the partial UniqueConstraint below can replace it.
        migrations.AlterUniqueTogether(
            name="payment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="payment",
            name="merchant_prepare_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="merchant_confirm_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="raw_response",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("fintechhub", "Fintechhub"),
                    ("yookassa", "YooKassa"),
                    ("tinkoff", "Tinkoff"),
                    ("manual", "Manual"),
                ],
                default="fintechhub",
                max_length=30,
            ),
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_id", ""), _negated=True),
                fields=("provider", "provider_id"),
                name="unique_provider_payment_id",
            ),
        ),
    ]
