# Generated by Django 6.1 on 2026-08-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_region_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changepasswordlogs',
            name='new_password',
        ),
        migrations.RemoveField(
            model_name='changepasswordlogs',
            name='old_password',
        ),
        migrations.AddField(
            model_name='userotpverifications',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
