# Generated by Django 6.1 on 2026-08-09 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('callback', 'Callback'), ('price_request', 'Price request'), ('consultation', 'Consultation'), ('one_click', 'One-click buy')], default='callback', max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='leads_lead_status_e23abe_idx')],
            },
        ),
    ]
